package Usuario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import BD.BdPermissoes;
import Classes.Permissao;
import View.Menu;
import static View.TelaLogin.cont;
import static View.TelaLogin.id;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author Gabriel-Note
 */
public class MenuUser extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuUser() {
        initComponents();

        botoes();
        block();

        this.setLocationRelativeTo(null);
        URL url = this.getClass().getResource("/Imagens/melc.jpg");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setTitle("APLICATIVO DE CONTROLADORIA");
        this.setResizable(false);
    }

    public void botoes() {
        pintura.setVisible(false);
        estoquePa.setVisible(false);
        Recebimento.setVisible(false);
        admIndustrial.setVisible(false);
        recepcao.setVisible(false);
        vendas.setVisible(false);
        compras.setVisible(false);
        estoqueMP.setVisible(false);
        rh.setVisible(false);
        manutencao.setVisible(false);
        segurança.setVisible(false);
        ferramentaria.setVisible(false);
        injecao.setVisible(false);
        financeiro.setVisible(false);
        controladoria.setVisible(false);

        Adiretoria.setVisible(false);
        Logistica.setVisible(false);
        Acabamento.setVisible(false);
         Moinho.setVisible(false);
          Portaria.setVisible(false);
           SGQ.setVisible(false);
         Administrativo.setVisible(false);
    }

    public void block() {
        BdPermissoes dao = new BdPermissoes();

        Permissao p = dao.perread(id);

        if (p.getEstoquePA().equals("Permitido")) {
            estoquePa.setVisible(true);
        }
        if (p.getRecebimento().equals("Permitido")) {
            Recebimento.setVisible(true);
        }
        if (p.getAdmIndustrial().equals("Permitido")) {
            admIndustrial.setVisible(true);
        }
        if (p.getRecpecao().equals("Permitido")) {
            recepcao.setVisible(true);
        }
        if (p.getVendas().equals("Permitido")) {
            vendas.setVisible(true);
        }

        if (p.getCompras().equals("Permitido")) {
            compras.setVisible(true);
        }
        if (p.getEstoquedeMateria().equals("Permitido")) {
            estoqueMP.setVisible(true);
        }

        if (p.getPintura().equals("Permitido")) {
            pintura.setVisible(true);
        }
        if (p.getRh().equals("Permitido")) {
            rh.setVisible(true);
        }
        if (p.getCon().equals("Permitido")) {
            controladoria.setVisible(true);
        }
        if (p.getManutencao().equals("Permitido")) {
            manutencao.setVisible(true);
        }
        if (p.getSegurança().equals("Permitido")) {
            segurança.setVisible(true);
        }
        if (p.getFerramentaria().equals("Permitido")) {
            ferramentaria.setVisible(true);

        }
        if (p.getInjecao().equals("Permitido")) {
            injecao.setVisible(true);
        }
        if (p.getFinaceiro().equals("Permitido")) {
            financeiro.setVisible(true);
        }
        if (p.getAdiretoria().equals("Permitido")) {
            Adiretoria.setVisible(true);

        }
        if (p.getLogistica().equals("Permitido")) {
            Logistica.setVisible(true);
        }
        if (p.getAcabamento().equals("Permitido")) {
            Acabamento.setVisible(true);
        }
        
         if (p.getMoinho().equals("Permitido")) {
            Moinho.setVisible(true);
        }
          if (p.getPortaria().equals("Permitido")) {
            Portaria.setVisible(true);
        }
 if (p.getSGQ().equals("Permitido")) {
            SGQ.setVisible(true);
        }
  if (p.getAdministratvo().equals("Permitido")) {
            Administrativo.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuarios2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        pintura = new javax.swing.JToggleButton();
        estoquePa = new javax.swing.JToggleButton();
        Recebimento = new javax.swing.JToggleButton();
        admIndustrial = new javax.swing.JToggleButton();
        recepcao = new javax.swing.JToggleButton();
        vendas = new javax.swing.JToggleButton();
        compras = new javax.swing.JToggleButton();
        estoqueMP = new javax.swing.JToggleButton();
        rh = new javax.swing.JToggleButton();
        manutencao = new javax.swing.JToggleButton();
        segurança = new javax.swing.JToggleButton();
        ferramentaria = new javax.swing.JToggleButton();
        injecao = new javax.swing.JToggleButton();
        financeiro = new javax.swing.JToggleButton();
        controladoria = new javax.swing.JToggleButton();
        Adiretoria = new javax.swing.JToggleButton();
        Logistica = new javax.swing.JToggleButton();
        Acabamento = new javax.swing.JToggleButton();
        Portaria = new javax.swing.JToggleButton();
        SGQ = new javax.swing.JToggleButton();
        Administrativo = new javax.swing.JToggleButton();
        Moinho = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Usuarios2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Usuarios2.setText("Usuarios");
        Usuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuarios2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(738, 418));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Usuario.setText("Menu de setores");
        Usuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                UsuarioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 280, 54));

        Sair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jPanel1.add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 110, 30));

        pintura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pintura.setText("Pintura");
        pintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinturaActionPerformed(evt);
            }
        });
        jPanel1.add(pintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 140, 30));

        estoquePa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        estoquePa.setText("Estoque PA");
        estoquePa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoquePaActionPerformed(evt);
            }
        });
        jPanel1.add(estoquePa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 190, 30));

        Recebimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Recebimento.setText("Recebimento");
        Recebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebimentoActionPerformed(evt);
            }
        });
        jPanel1.add(Recebimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 140, 30));

        admIndustrial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        admIndustrial.setText("Adm Industrial");
        admIndustrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admIndustrialActionPerformed(evt);
            }
        });
        jPanel1.add(admIndustrial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 140, 30));

        recepcao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        recepcao.setText("Recepção");
        recepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepcaoActionPerformed(evt);
            }
        });
        jPanel1.add(recepcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 30));

        vendas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        vendas.setText("Vendas");
        vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasActionPerformed(evt);
            }
        });
        jPanel1.add(vendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, 30));

        compras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        compras.setText("Compras");
        compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasActionPerformed(evt);
            }
        });
        jPanel1.add(compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 140, 30));

        estoqueMP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        estoqueMP.setText("Estoque de Materia P.");
        estoqueMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueMPActionPerformed(evt);
            }
        });
        jPanel1.add(estoqueMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 30));

        rh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rh.setText("Rh/Dp");
        rh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rhActionPerformed(evt);
            }
        });
        jPanel1.add(rh, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 140, 30));

        manutencao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        manutencao.setText("Manutenção");
        manutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manutencaoActionPerformed(evt);
            }
        });
        jPanel1.add(manutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 140, 30));

        segurança.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        segurança.setText("Segurança do Trabalho");
        segurança.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segurançaActionPerformed(evt);
            }
        });
        jPanel1.add(segurança, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 190, 30));

        ferramentaria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ferramentaria.setText("Ferramentaria");
        ferramentaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ferramentariaActionPerformed(evt);
            }
        });
        jPanel1.add(ferramentaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 140, 30));

        injecao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        injecao.setText("Injeção");
        injecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                injecaoActionPerformed(evt);
            }
        });
        jPanel1.add(injecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 140, 30));

        financeiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        financeiro.setText("Financeiro");
        financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeiroActionPerformed(evt);
            }
        });
        jPanel1.add(financeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 140, 30));

        controladoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        controladoria.setText("Controladoria");
        controladoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controladoriaActionPerformed(evt);
            }
        });
        jPanel1.add(controladoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 140, 30));

        Adiretoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Adiretoria.setText("Apoio diretoria");
        Adiretoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdiretoriaActionPerformed(evt);
            }
        });
        jPanel1.add(Adiretoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 30));

        Logistica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Logistica.setText("Expedição/Logistica");
        Logistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogisticaActionPerformed(evt);
            }
        });
        jPanel1.add(Logistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 190, 30));

        Acabamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Acabamento.setText("Acabamento");
        Acabamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcabamentoActionPerformed(evt);
            }
        });
        jPanel1.add(Acabamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 140, 30));

        Portaria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Portaria.setText("Portaria");
        Portaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortariaActionPerformed(evt);
            }
        });
        jPanel1.add(Portaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 140, 30));

        SGQ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SGQ.setText("Contabilidade");
        SGQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SGQActionPerformed(evt);
            }
        });
        jPanel1.add(SGQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 140, 30));

        Administrativo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Administrativo.setText("Administrativo");
        Administrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministrativoActionPerformed(evt);
            }
        });
        jPanel1.add(Administrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 140, 30));

        Moinho.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Moinho.setText("Moinho");
        Moinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Moinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDO Tablea.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 750, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDO Tablea.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Usuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuarios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuarios2ActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void UsuarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_UsuarioAncestorAdded

    }//GEN-LAST:event_UsuarioAncestorAdded

    private void pinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinturaActionPerformed
        PlanilhaPintura tl = new PlanilhaPintura();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pinturaActionPerformed

    private void estoquePaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoquePaActionPerformed
        PlanilhaEstoquePa tl = new PlanilhaEstoquePa();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_estoquePaActionPerformed

    private void RecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebimentoActionPerformed
        PlanilhaRecebimento tl = new PlanilhaRecebimento();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RecebimentoActionPerformed

    private void admIndustrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admIndustrialActionPerformed
        PlanilhaAdmIndustrial tl = new PlanilhaAdmIndustrial();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_admIndustrialActionPerformed

    private void recepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepcaoActionPerformed
        PlanilhaRecepcao tl = new PlanilhaRecepcao();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_recepcaoActionPerformed

    private void vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasActionPerformed
        PlanilhaVendas tl = new PlanilhaVendas();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vendasActionPerformed

    private void comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasActionPerformed
        PlanilhaCompras tl = new PlanilhaCompras();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_comprasActionPerformed

    private void estoqueMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueMPActionPerformed
        PlanilhaEstouqedeMateriaP tl = new PlanilhaEstouqedeMateriaP();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_estoqueMPActionPerformed

    private void rhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rhActionPerformed
        PlanilhaRh tl = new PlanilhaRh();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rhActionPerformed

    private void manutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manutencaoActionPerformed
        Planilhamanutencao tl = new Planilhamanutencao();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manutencaoActionPerformed

    private void segurançaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segurançaActionPerformed
        PlanilhaSegurançadoTrabalho tl = new PlanilhaSegurançadoTrabalho();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_segurançaActionPerformed

    private void ferramentariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ferramentariaActionPerformed
        PlanilhaFerramentaria tl = new PlanilhaFerramentaria();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ferramentariaActionPerformed

    private void injecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_injecaoActionPerformed
        PlanilhaInjecao tl = new PlanilhaInjecao();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_injecaoActionPerformed

    private void financeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeiroActionPerformed
        Planilhafinanceiro tl = new Planilhafinanceiro();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_financeiroActionPerformed

    private void controladoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controladoriaActionPerformed
        PlanilhaControladoria tl = new PlanilhaControladoria();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_controladoriaActionPerformed

    private void AdiretoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdiretoriaActionPerformed
        PlanilhaApoio_diretoria tl = new PlanilhaApoio_diretoria();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdiretoriaActionPerformed

    private void LogisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogisticaActionPerformed
        PlanilhaLogistica tl = new PlanilhaLogistica();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogisticaActionPerformed

    private void AcabamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcabamentoActionPerformed
        PlanilhaAcabamento tl = new PlanilhaAcabamento();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AcabamentoActionPerformed

    private void PortariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortariaActionPerformed
  PlanilhaPortaria tl = new PlanilhaPortaria();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PortariaActionPerformed

    private void SGQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SGQActionPerformed
     PlanilhaSGQ tl = new PlanilhaSGQ();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SGQActionPerformed

    private void AdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministrativoActionPerformed
    PlanilhaAdministrativo tl = new PlanilhaAdministrativo();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdministrativoActionPerformed

    private void MoinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoinhoActionPerformed
        PlanilhaMoinho tl = new PlanilhaMoinho();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MoinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Acabamento;
    private javax.swing.JToggleButton Adiretoria;
    private javax.swing.JToggleButton Administrativo;
    private javax.swing.JToggleButton Logistica;
    private javax.swing.JToggleButton Moinho;
    private javax.swing.JToggleButton Portaria;
    private javax.swing.JToggleButton Recebimento;
    private javax.swing.JToggleButton SGQ;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel Usuario;
    private javax.swing.JToggleButton Usuarios2;
    private javax.swing.JToggleButton admIndustrial;
    private javax.swing.JToggleButton compras;
    private javax.swing.JToggleButton controladoria;
    private javax.swing.JToggleButton estoqueMP;
    private javax.swing.JToggleButton estoquePa;
    private javax.swing.JToggleButton ferramentaria;
    private javax.swing.JToggleButton financeiro;
    private javax.swing.JToggleButton injecao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton manutencao;
    private javax.swing.JToggleButton pintura;
    private javax.swing.JToggleButton recepcao;
    private javax.swing.JToggleButton rh;
    private javax.swing.JToggleButton segurança;
    private javax.swing.JToggleButton vendas;
    // End of variables declaration//GEN-END:variables
}
