/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import BD.BD;
import Classes.Funcionario;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable.PrintMode;

/**
 *
 * @author Samuelson
 */
public class Planilha extends javax.swing.JFrame {

    /**
     * Creates new form ViewJTable
     */
    public Planilha() {
        initComponents();
        Busca.addItem("Funcionario");
        Busca.addItem("cargo");
        Busca.addItem("Setor");

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        jTProdutos.setRowSorter(new TableRowSorter(modelo));

        readJTable();
        this.setLocationRelativeTo(null);
        URL url = this.getClass().getResource("/Imagens/melc.jpg");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        this.setTitle("APLICATIVO DE CONTROLADORIA");
        this.setResizable(false);
    }

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        BD pdao = new BD();

        for (Funcionario p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getFunc(),
                p.getAdmicao(),
                p.getSetor(),
                p.getCargo(),
                p.getSalario(),
                p.getSalariomensal(),
                p.getEncargos(),
                p.getConvmed(),
                p.getSeis(),
                p.getValetrans(),
                p.getCestaBasica(),
                p.getBeneficio(),
                p.getCustot(),});

        }

    }

    public void readJTableForfenc(String desc) {

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        BD pdao = new BD();

        for (Funcionario p : pdao.readForFuncionario(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getFunc(),
                p.getAdmicao(),
                p.getSetor(),
                p.getCargo(),
                p.getSalario(),
                p.getSalariomensal(),
                p.getEncargos(),
                p.getConvmed(),
                p.getSeis(),
                p.getValetrans(),
                p.getCestaBasica(),
                p.getBeneficio(),
                p.getCustot(),});
        }
    }

    public void readJTableForcar(String desc) {

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        BD pdao = new BD();

        for (Funcionario p : pdao.readForcargo(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getFunc(),
                p.getAdmicao(),
                p.getSetor(),
                p.getCargo(),
                p.getSalario(),
                p.getSalariomensal(),
                p.getEncargos(),
                p.getConvmed(),
                p.getSeis(),
                p.getValetrans(),
                p.getCestaBasica(),
                p.getBeneficio(),
                p.getCustot(),});

        }

    }

    public void readJTableForsetor(String desc) {

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        BD pdao = new BD();

        for (Funcionario p : pdao.readForsetor(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getFunc(),
                p.getAdmicao(),
                p.getSetor(),
                p.getCargo(),
                p.getSalario(),
                p.getSalariomensal(),
                p.getEncargos(),
                p.getConvmed(),
                p.getSeis(),
                p.getValetrans(),
                p.getCestaBasica(),
                p.getBeneficio(),
                p.getCustot(),});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        Voltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Apagar = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Busca = new java.awt.Choice();
        txtBuscaDesc = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        impressao = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Funcionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admissao = new javax.swing.JTextField();
        setor = new javax.swing.JTextField();
        cargo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        SalarioMensal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        encargos = new javax.swing.JTextField();
        covmedico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        seis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valtransporte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cestabasica = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        beneficios = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ctotal = new javax.swing.JTextField();
        calaculabene = new javax.swing.JButton();
        calculatot = new javax.swing.JButton();
        calculatudo = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 595));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Funcionario", "Admissão", "Setor", "Cargo", "Salario", "Salario Mensal", "Encargos", "Convênio medico", "6%", "Vale Transporte", "Cesta Basica", "Beneficios", "Custo Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutosMouseClicked(evt);
            }
        });
        jTProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTProdutos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1348, 324));

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel3.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 100, 20));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 83, -1));

        Apagar.setText("Apagar tudo");
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });
        jPanel3.add(Apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 110, -1));

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 86, -1));

        Busca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Busca.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                BuscaComponentHidden(evt);
            }
        });
        jPanel3.add(Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 90, 20));
        jPanel3.add(txtBuscaDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 253, 20));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, 20));

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jPanel3.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 100, 20));

        impressao.setText("Imprimir");
        impressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impressaoActionPerformed(evt);
            }
        });
        jPanel3.add(impressao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 100, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDO Tablea.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1410, 490));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 1360, 440));

        Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(Funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, -1));

        jLabel1.setText("Funcionario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Admissão");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        admissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissaoActionPerformed(evt);
            }
        });
        getContentPane().add(admissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 100, -1));

        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        getContentPane().add(setor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 86, -1));

        cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoActionPerformed(evt);
            }
        });
        getContentPane().add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 170, 20));

        jLabel4.setText("Cargo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 20));

        jLabel3.setText("Setor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel5.setText("Salario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioActionPerformed(evt);
            }
        });
        getContentPane().add(salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 100, -1));

        SalarioMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioMensalActionPerformed(evt);
            }
        });
        getContentPane().add(SalarioMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 100, -1));

        jLabel6.setText("Salario mensal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabel7.setText("Encargos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        encargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encargosActionPerformed(evt);
            }
        });
        getContentPane().add(encargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, -1));

        covmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                covmedicoActionPerformed(evt);
            }
        });
        getContentPane().add(covmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, -1));

        jLabel8.setText("Convênio medico");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        getContentPane().add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 100, -1));

        jLabel9.setText("6%");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        valtransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valtransporteActionPerformed(evt);
            }
        });
        getContentPane().add(valtransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 100, -1));

        jLabel10.setText("Vale Transporte");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        cestabasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cestabasicaActionPerformed(evt);
            }
        });
        getContentPane().add(cestabasica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        jLabel11.setText("Cesta Basica");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        beneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beneficiosActionPerformed(evt);
            }
        });
        getContentPane().add(beneficios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 30, 120, 20));

        jLabel12.setText("Beneficios");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        jLabel13.setText("Custo total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 70, -1, -1));

        ctotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctotalActionPerformed(evt);
            }
        });
        getContentPane().add(ctotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 90, 130, 20));

        calaculabene.setText("Calcular Beneficios");
        calaculabene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calaculabeneActionPerformed(evt);
            }
        });
        getContentPane().add(calaculabene, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, 20));

        calculatot.setText("Calcular Custo total");
        calculatot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatotActionPerformed(evt);
            }
        });
        getContentPane().add(calculatot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 160, 20));

        calculatudo.setText("Calcular tudo");
        calculatudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatudoActionPerformed(evt);
            }
        });
        getContentPane().add(calculatudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 150, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDO Tablea.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutosMouseClicked
        // TODO add your handling code here:

        if (jTProdutos.getSelectedRow() != -1) {

            Funcionario.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 1).toString());
            admissao.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
            setor.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());
            cargo.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 4).toString());
            salario.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 5).toString());
            SalarioMensal.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 6).toString());
            encargos.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 7).toString());
            covmedico.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 8).toString());
            seis.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 9).toString());
            valtransporte.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 10).toString());
            cestabasica.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 11).toString());
            beneficios.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 12).toString());
            ctotal.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 13).toString());

        }

    }//GEN-LAST:event_jTProdutosMouseClicked

    private void jTProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProdutosKeyReleased
        // TODO add your handling code here:

        if (jTProdutos.getSelectedRow() != -1) {

            Funcionario.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 1).toString());
            admissao.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 2).toString());
            setor.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 3).toString());
            cargo.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 4).toString());
            salario.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 5).toString());
            SalarioMensal.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 6).toString());
            encargos.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 7).toString());
            covmedico.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 8).toString());
            seis.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 9).toString());
            valtransporte.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 10).toString());
            cestabasica.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 11).toString());
            beneficios.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 12).toString());
            ctotal.setText(jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 13).toString());
        }

    }//GEN-LAST:event_jTProdutosKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String op;
        op = Busca.getSelectedItem().toString();
        if (op.equals("cargo")) {
            readJTableForcar(txtBuscaDesc.getText());

        } else if (op.equals("Setor")) {
            readJTableForsetor(txtBuscaDesc.getText());
        } else {

            readJTableForfenc(txtBuscaDesc.getText());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        // TODO add your handling code here:
        boolean s = campo_vazio();

        if (s = true) {
            if (jTProdutos.getSelectedRow() != -1) {

                Funcionario p = new Funcionario();
                System.out.print(p.getEncargos());
                BD dao = new BD();

                p.setFunc(Funcionario.getText());
                p.setAdmicao(admissao.getText());
                p.setSetor(setor.getText().toLowerCase());
                p.setCargo(cargo.getText());
                p.setSalario(Double.parseDouble(salario.getText()));
                p.setSalariomensal(Double.parseDouble(SalarioMensal.getText()));
                p.setEncargos(Double.parseDouble(encargos.getText()));
                p.setConvmed(Double.parseDouble(covmedico.getText()));
                p.setSeis(Double.parseDouble(seis.getText()));
                p.setValetrans(Double.parseDouble(valtransporte.getText()));
                p.setCestaBasica(Double.parseDouble(cestabasica.getText()));
                p.setBeneficio(Double.parseDouble(beneficios.getText()));

                p.setCustot(Double.parseDouble(ctotal.getText()));

                p.setId((int) jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0));
                dao.update(p);

                apagar();

                readJTable();

            }
        }
    }//GEN-LAST:event_AtualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //        System.out.println("Linha selecionada: "+jTProdutos.getSelectedRow());
        if (jTProdutos.getSelectedRow() != -1) {

            Funcionario p = new Funcionario();
            BD dao = new BD();

            p.setId((int) jTProdutos.getValueAt(jTProdutos.getSelectedRow(), 0));

            dao.delete(p);

            apagar();

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    private double calculabene(double Vtran, double cestabas,double med) {

        double result = Vtran + cestabas+med;

        return result;
    }

    private double calculaTot(double bene, double emcanr, double salar) {

        double result = bene + emcanr + salar;

        return result;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        boolean s = campo_vazio();

        if (s = true) {

            Funcionario p = new Funcionario();
            BD dao = new BD();

            p.setFunc(Funcionario.getText());
            p.setAdmicao(admissao.getText());
            p.setSetor(setor.getText().toLowerCase());
            p.setCargo(cargo.getText());
            p.setSalario(Double.parseDouble(salario.getText()));
            p.setSalariomensal(Double.parseDouble(SalarioMensal.getText()));
            p.setEncargos(Double.parseDouble(encargos.getText()));
            p.setConvmed(Double.parseDouble(covmedico.getText()));
            p.setSeis(Double.parseDouble(seis.getText()));
            p.setValetrans(Double.parseDouble(valtransporte.getText()));
            p.setCestaBasica(Double.parseDouble(cestabasica.getText()));
            p.setBeneficio(Double.parseDouble(beneficios.getText()));
            p.setCustot(Double.parseDouble(ctotal.getText()));

            dao.create(p);

            apagar();
            readJTable();

//        DefaultTableModel dtmProdutos = (DefaultTableModel) jTProdutos.getModel();
//       Object[] dados = {txtDesc.getText(), txtQtd.getText(), txtPreco.getText()};
//       dtmProdutos.addRow(dados);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public Boolean campo_vazio() {
        boolean status;
        if (Funcionario.getText().trim().equals("") || admissao.getText().trim().equals("") || setor.getText().trim().equals("") || cargo.getText().trim().equals("") || salario.getText().trim().equals("") || SalarioMensal.getText().trim().equals("")
                || encargos.getText().trim().equals("") || covmedico.getText().trim().equals("") || seis.getText().trim().equals("") || valtransporte.getText().trim().equals("") || cestabasica.getText().trim().equals("") || beneficios.getText().trim().equals("") || ctotal.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "campo em branco");
            status = false;
            
        } else {
            status = true;
        }
        return status;
    }

    private void FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncionarioActionPerformed

    private void admissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admissaoActionPerformed

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setorActionPerformed

    private void cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoActionPerformed

    private void salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioActionPerformed

    private void SalarioMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioMensalActionPerformed

    private void encargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encargosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encargosActionPerformed

    private void covmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_covmedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_covmedicoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seisActionPerformed

    private void valtransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valtransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valtransporteActionPerformed

    private void cestabasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cestabasicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cestabasicaActionPerformed

    private void beneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beneficiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beneficiosActionPerformed

    private void ctotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctotalActionPerformed
    public void apagar() {
        Funcionario.setText("");
        admissao.setText("");
        setor.setText("");
        cargo.setText("");
        salario.setText("");
        SalarioMensal.setText("");
        encargos.setText("");
        covmedico.setText("");
        seis.setText("");
        valtransporte.setText("");
        cestabasica.setText("");
        beneficios.setText("");
        ctotal.setText("");
    }
    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
        apagar();
    }//GEN-LAST:event_ApagarActionPerformed

    public void CalculaBeneficio() {
        double a = Double.parseDouble(valtransporte.getText());
        double b = Double.parseDouble(cestabasica.getText());
         double c = Double.parseDouble(covmedico.getText());
        double tot = calculabene(a, b, c);
        tot *= 100;
        tot = Math.round(tot);
        tot /= 100;
        beneficios.setText(String.valueOf(tot));
    }
    private void calaculabeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calaculabeneActionPerformed
        CalculaBeneficio();

    }//GEN-LAST:event_calaculabeneActionPerformed
    public void CalculaTotal() {
        double a = Double.parseDouble(beneficios.getText());
        double b = Double.parseDouble(encargos.getText());
        double c = Double.parseDouble(SalarioMensal.getText());
        double tot = calculaTot(a, b, c);

        tot *= 100;
        tot = Math.round(tot);
        tot /= 100;

        ctotal.setText(String.valueOf(tot));
    }
    private void calculatotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatotActionPerformed
        CalculaTotal();

    }//GEN-LAST:event_calculatotActionPerformed

    private void BuscaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BuscaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaComponentHidden

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        Menu tl = new Menu();
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void impressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impressaoActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(jTProdutos.getPrintable(PrintMode.FIT_WIDTH, null, null));
        job.setJobName("jTProdutos");
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(Planilha.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_impressaoActionPerformed

    private void calculatudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatudoActionPerformed
        CalculaBeneficio();
        CalculaTotal();

    }//GEN-LAST:event_calculatudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planilha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar;
    private javax.swing.JButton Atualizar;
    private java.awt.Choice Busca;
    private javax.swing.JTextField Funcionario;
    private javax.swing.JTextField SalarioMensal;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField admissao;
    private javax.swing.JTextField beneficios;
    private javax.swing.JButton calaculabene;
    private javax.swing.JButton calculatot;
    private javax.swing.JButton calculatudo;
    private javax.swing.JTextField cargo;
    private javax.swing.JTextField cestabasica;
    private javax.swing.JTextField covmedico;
    private javax.swing.JTextField ctotal;
    private javax.swing.JTextField encargos;
    private javax.swing.JButton impressao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JButton sair;
    private javax.swing.JTextField salario;
    private javax.swing.JTextField seis;
    private javax.swing.JTextField setor;
    private javax.swing.JTextField txtBuscaDesc;
    private javax.swing.JTextField valtransporte;
    // End of variables declaration//GEN-END:variables
}
